# 清华大学源
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# 私有源
source 'https://github.com/kaibuleite/xSpecs.git'

use_frameworks!
platform :ios, '13.0'

target 'xWebBrowser_Example' do
  pod 'xWebBrowser', :path => '../'

  target 'xWebBrowser_Tests' do
    inherit! :search_paths

    
  end
end
